Messages:
  JLogin-Help: "&7[&bJLogin&7] &f/jlogin unregister|changepassword"
  No-Permission: "&7[&bJLogin&7] &fYou don't have permission: {permission} !"

  Already-Registered: "&7[&bJLogin&7] &fYou are already registered!"
  Successfully-Registered: "&7[&bJLogin&7] &fSuccessfully registered!"
  Registered-Usage: "&7[&bJLogin&7] &fUsage: /register <password>"

  Already-Logged-In: "&7[&bJLogin&7] &fYou are already logged in!"
  Successfully-Logged-In: "&7[&bJLogin&7] &fSuccessfully logged in!"
  Login-Usage: "&7[&bJLogin&7] &fUsage: /login <password>"

  Wrong-Password: "&7[&bJLogin&7] &fWrong password! Please try again!"

  Not-Registered: "&7[&bJLogin&7] &fYou are not registered! Please type /register <password> to register"
  Not-Logged-In: "&7[&bJLogin&7] &fYou are not logged in! Please type /login <password> to log in"

  Change-Password-Usage: "&7[&bJLogin&7] &fUsage: /changepassword <oldpassword> <newpassword>"
  Change-Password-Other-Usage: "&7[&bJLogin&7] &fUsage: /jlogin changepassword <player> <newpassword>"
  Password-Changed: "&7[&bJLogin&7] &fSuccessfully changed your password!"
  Password-Changed-Other: "&7[&bJLogin&7] &fSuccessfully changed {player} password!"

  Unregister-Usage: "&7[&bJLogin&7] &fUsage: /jlogin unregister <player>"
  Unregistered-Player: "&7[&bJLogin&7] {player} has been unregistered"

  Player-Not-Found: "&7[&bJLogin&7] &f{player} is not registered in the database!"