#set to [] to disable messages
Messages:
  Already-Registered:
    - "&aYou are already registered!"
  Successfully-Registered:
    - "&aSuccessfully registered!"
  Registered-Usage:
    - "&6&lJLogin &7> &e/register <password> {captcha}"
  Already-Logged-In:
    - "&aYou are already logged in!"
  Successfully-Logged-In:
    - "&aSuccessfully logged in!"
  Login-Usage:
    - "&6&lJLogin &7> &eUsage: /login <password> {captcha}"
  Wrong-Password:
    - "&cWrong password! Please try again!"
  Not-Registered:
    - "&8&m                                                                          &8"
    - ""
    - "      &eYou are not registered!"
    - "      &a/register <password> &c{captcha}"
    - ""
    - "&8&m                                                                          &8"
  Not-Logged-In:
    - "&8&m                                                                          &8"
    - ""
    - "      &eYou are not logged in!"
    - "      &a/login <password> &c{captcha}"
    - ""
    - "&8&m                                                                          &8"
  Change-Password-Usage:
    - "&6&lJLogin &7> &eUsage: /changepassword <oldpassword> <newpassword>"
  Password-Changed:
    - "&aSuccessfully changed your password!"
  Wrong-Captcha:
    - "&cWrong Captcha!, please try again!"

#set to "" to disable titles
Titles:
  Registered: "&a&lJLogin | &eSuccessfully registered"
  Not-Registered: "&a&lJLogin | &eYour captcha: &c{captcha}"
  Logged-In: "&a&lJLogin | &eSuccessfully logged in"
  Not-Logged-In: "&a&lJLogin | &eYour captcha: &c{captcha}"