name: JLogin
main: com.josemarcellio.jlogin.JLogin
version: 1.4
author: JoseMarcellio
description: A lightweight login system by JoseMarcellio
commands:
  register:
    aliases: []
  login:
    aliases: []
  changepassword:
    aliases: []
  jlogin:
    aliases: []
