name: JLogin
main: com.josemarcellio.jlogin.JLogin
version: 1.3
author: JoseMarcellio
description: A lightweight login system by JoseMarcellio
commands:
  register:
  login:
  changepassword:
  jlogin:
